import { useEffect } from 'react';
import Head from 'next/head'
import bot from '@/utils/bot'

export default function Home() {
  useEffect(() => {
    console.log('Starting bot...');
    bot.on('polling_error', (error) => {
      console.error(error);
    });
  }, []);
  
  return (
    <>
      <Head>
        <title>Artisan Bot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Telegram bot that edits and makes arts with your photos</p>
    </>
  )
}
