import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Artisan Bot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Telegram bot that edits and makes arts with your photos</p>
    </>
  )
}
